[build]
publish = "dist"
command = "pnpm run build"

[build.environment]
NODE_VERSION = "20"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
  from = "/api/**/pokemon"
  to = "https://pokeapi.co/api/v2/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/**/rickAndMorty"
  to = "https://rickandmortyapi.com/api/:splat"
  status = 200
  force = true
